include:
  - project: 'larvata/devops/gitlab-ci-templates'
    ref: master
    file: 'Jobs/Sonar-Test.gitlab-ci.yml'
    
stages:
  - build
  - test
  - deploy

variables:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  # required
  XCODE_SCHEME_NAME: ""
  XCODE_PRODUCT_NAME: ""
  # optional
  FASTLANE_ADHOC_METHOD: fabric

archive_adhoc_app:
  stage: build
  tags:
    - macOS
  except:
    - master
    - tags
  variables:
    XCODE_SCHEME: "$XCODE_SCHEME_NAME $CI_COMMIT_REF_SLUG"
  script:
    - bundle install
    - bundle exec pod install
    - git config --global credential.helper store
    - echo "https://larvata_taiwan:${GIT_PASS}@bitbucket.org" > ~/.git-credentials
    - bundle exec fastlane ios archive_adhoc --verbose
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${XCODE_PRODUCT_NAME}-${CI_COMMIT_REF_SLUG}.ipa
      - ${XCODE_PRODUCT_NAME}-${CI_COMMIT_REF_SLUG}.app.dSYM.zip
      
archive_staging_app:
  stage: build
  tags:
    - macOS
  only:
    - master
  variables:
    XCODE_SCHEME: "$XCODE_SCHEME_NAME staging"
  script:
    - bundle install
    - bundle exec pod install
    - git config --global credential.helper store
    - echo "https://larvata_taiwan:${GIT_PASS}@bitbucket.org" > ~/.git-credentials
    - bundle exec fastlane ios archive_adhoc --verbose
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${XCODE_PRODUCT_NAME}-staging.ipa
      - ${XCODE_PRODUCT_NAME}-staging.app.dSYM.zip

archive_appstore_app:
  stage: build
  tags:
    - macOS
  only:
    - tags
  variables:
    XCODE_SCHEME: $XCODE_SCHEME_NAME
  script:
    - bundle install
    - bundle exec pod install
    - git config --global credential.helper store
    - echo "https://larvata_taiwan:${GIT_PASS}@bitbucket.org" > ~/.git-credentials
    - bundle exec fastlane ios archive_appstore --verbose
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${XCODE_PRODUCT_NAME}.ipa
      - ${XCODE_PRODUCT_NAME}.app.dSYM.zip

deploy_adhoc_app:
  stage: deploy
  tags:
    - macOS
  except:
    - master
    - tags
  script:
    - bundle install
    - bundle exec pod install
    - bundle exec fastlane ios beta_${FASTLANE_ADHOC_METHOD} --verbose
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${XCODE_PRODUCT_NAME}-${CI_COMMIT_REF_SLUG}.ipa
      - ${XCODE_PRODUCT_NAME}-${CI_COMMIT_REF_SLUG}.app.dSYM.zip
      
deploy_staging_app:
  stage: deploy
  tags:
    - macOS
  only:
    - master
  script:
    - bundle install
    - bundle exec pod install
    - bundle exec fastlane ios beta_${FASTLANE_ADHOC_METHOD} --verbose
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${XCODE_PRODUCT_NAME}-staging.ipa
      - ${XCODE_PRODUCT_NAME}-staging.app.dSYM.zip

deploy_appstore_app:
  stage: deploy
  tags:
    - macOS
  only:
    - tags
  script:
    - bundle install
    - bundle exec pod install
    - bundle exec fastlane ios beta_testflight --verbose
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${XCODE_PRODUCT_NAME}.ipa
      - ${XCODE_PRODUCT_NAME}.app.dSYM.zip