include:
  - remote: 'https://raw.githubusercontent.com/LarvataTW/larvata-fastlane-ios/master/iOS-Fastlane.gitlab-ci.yml'
  - remote: "https://raw.githubusercontent.com/LarvataTW/gitlab-ci-templates/master/Jobs/Sonar-Test.gitlab-ci.yml"