sonar_testing:
  stage: test
  image:
    name: newtmitch/sonar-scanner
    entrypoint:
      - /bin/bash
  script:
    - >
      sonar-scanner
      -Dsonar.projectName=${CI_PROJECT_PATH_SLUG}
      -Dsonar.projectKey=${CI_PROJECT_PATH_SLUG}
      -Dsonar.projectBaseDir=${CI_PROJECT_DIR}
      -Dsonar.sources=.
      -Dsonar.host.url=https://sonar.atavral.ninja
      -Dsonar.login=${SONAR_TOKEN}
