# This is an example file for tasks in Jobs/Prepare.gitlab-ci.yml
# Those config values will map into Gitlab project's setting configuration.
#
# refs: https://github.com/LarvataTW/gitlab-utils/blob/main/.gitlab/settings.yaml
