prepare:
  stage: prepare
  image: "ghcr.io/larvatatw/gitlab-utils:latest"
  variables:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: "localhost,127.0.0.1,.your.internal.domain"
    GITLAB_BASE_URL: $CI_SERVER_URL
    GITLAB_SETTING_FILE: ".gitlab/settings.yaml"
  script:
    - |
      if [[ -z "$GITLAB_PRIVATE_TOKEN" ]] || [[ ! -f "$GITLAB_SETTING_FILE" ]]; then
        echo "Do nothing."
      else
        echo "Creating CI/CD variables for this project according to the $GITLAB_SETTING_FILE file ..."
        python /app/main.py
      fi
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
