prepare:
  stage: prepare
  image: "ghcr.io/larvatatw/gitlab-utils:latest"
  variables:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: "localhost,127.0.0.1,.your.internal.domain"
    GITLAB_SETTING_FILE: ".gitlab/settings.yaml"
  script:
    - |
      if [[ -z "$GITLAB_PRIVATE_TOKEN" ]]; then
        python /app/main.py
        echo "Creating CI/CD variables for this project according to the $GITLAB_SETTING_FILE file.\n"
      else
        echo "Do nothing.\n"
      fi
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
    - exists:
      - $GITLAB_SETTING_FILE
