prepare:
  stage: prepare
  image: "ghcr.io/larvatatw/gitlab-utils:latest"
  variables:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: "localhost,127.0.0.1,.your.internal.domain"
    GITLAB_SETTING_FILE: ".gitlab/settings.yaml"
  script:
    - |
      # Setup CI/CD variables
      if [[ -z "$GITLAB_PRIVATE_TOKEN" ]] && [[ -z "$GITLAB_BASE_URL" ]]; then
        python /app/main.py
      else
        echo "do nothing"
      fi
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
